title: Relación de un viaje al Río de la Plata
email: hdcaicyt@gmail.com
description: y de allí por tierra al Perú con observaciones sobre los habitantes, sean indios o españoles, las ciudades, el comercio, la fertilidad y las riquezas de esta parte de América
baseurl: "/Relacion-de-un-viaje" # the subpath of your site, e.g. /blog
url: "http://hdlab.space" # the base hostname & protocol for your site
github_repo: Relacion-de-un-viaje # the GitHub repo name for your project
twitter_username: HDCAICYT
github_username:  hdcaicyt
facebook_username: HDCAICYTLAB

social_link: twitter
social_username: hdcaicyt

theme_color: light

# Build settings
markdown: kramdown

collections:
    acarete_pages:
      output: true
    recursos:
      output: true
    nombres_destacados:
      output: true
    flora_fauna:
      output: true
